### ISSUE TITLE
app startup failing

### ISSUE THREAD

**Issue by MayurAgarkar** [snapcrescent/snapcrescent#15]
Hi, 

I am setting this up on my unraid server. 
I have mysql setup and connect to it using console. 
However the spring app is failing at start up and fails so fast that I could not grab all the logs neede. but I managed to capture following: 

`Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset path-independent::create_album_asset_assn::navalgandhi1989:
     Reason: liquibase.exception.DatabaseException: Failed to open the referenced table 'album' [Failed SQL: (1824) CREATE TABLE IF NOT EXISTS `album_asset_assn` (  
  `album_id` BIGINT NOT NULL,
  `asset_id` BIGINT NOT NULL,
  PRIMARY KEY (`album_id`, `asset_id`) ,
  CONSTRAINT `fk_album_asset_assn_album_id` FOREIGN KEY (`album_id`) REFERENCES `snap_crescent`.`album`(`id`),
  CONSTRAINT `fk_album_asset_assn_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `snap_crescent`.`asset`(`id`)
)]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:297)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:295)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Liquibase.runInScope(Liquibase.java:2639)
        at liquibase.Liquibase.update(Liquibase.java:236)
        at liquibase.Liquibase.update(Liquibase.java:221)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 106 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset path-independent::create_album_asset_assn::navalgandhi1989:
     Reason: liquibase.exception.DatabaseException: Failed to open the referenced table 'album' [Failed SQL: (1824) CREATE TABLE IF NOT EXISTS `album_asset_assn` (  
  `album_id` BIGINT NOT NULL,
  `asset_id` BIGINT NOT NULL,
  PRIMARY KEY (`album_id`, `asset_id`) ,
  CONSTRAINT `fk_album_asset_assn_album_id` FOREIGN KEY (`album_id`) REFERENCES `snap_crescent`.`album`(`id`),
  CONSTRAINT `fk_album_asset_assn_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `snap_crescent`.`asset`(`id`)
)]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:744)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:59)
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:124)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:124)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:105)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:75)
        ... 124 common frames omitted
Caused by: liquibase.exception.DatabaseException: Failed to open the referenced table 'album' [Failed SQL: (1824) CREATE TABLE IF NOT EXISTS `album_asset_assn` (  
  `album_id` BIGINT NOT NULL,
  `asset_id` BIGINT NOT NULL,
  PRIMARY KEY (`album_id`, `asset_id`) ,
  CONSTRAINT `fk_album_asset_assn_album_id` FOREIGN KEY (`album_id`) REFERENCES `snap_crescent`.`album`(`id`),
  CONSTRAINT `fk_album_asset_assn_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `snap_crescent`.`asset`(`id`)
)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1270)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1252)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:702)
        ... 144 common frames omitted
Caused by: java.sql.SQLException: Failed to open the referenced table 'album'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441)
        ... 149 common frames omitted`

Any idea whats happening ? From my initial debugging, it seems the table is referencing foreign key before the other table is created. but I may be wrong. Any help appreciated. Thanks !

**Comment by MayurAgarkar** [comment]
Ahh, i did some debugging on your code, it seems the queries are hard coded instead of using the env variables provided in docker container. in my case I have a db named 'photodb' but queries are hardcoded to use 'snap_crescent' 

I think this needs enhancements to use the variable/dbname provided in container vars, if not, then fall back to default value.

**Comment by navalgandhi1989** [comment]
Fixed
